INSERT INTO gamma.countries (country_code, country_name) VALUES
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctica'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BR', 'Brazil'),
('BN', 'Brunei'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('CV', 'Cabo Verde'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CD', 'Congo, Democratic Republic of the'),
('CR', 'Costa Rica'),
('CI', 'Ivory Coast'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czechia'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('SZ', 'Eswatini'),
('ET', 'Ethiopia'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GR', 'Greece'),
('GD', 'Grenada'),
('GT', 'Guatemala'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HN', 'Honduras'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', 'Korea, North'),
('KR', 'Korea, South'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', 'Laos'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('MX', 'Mexico'),
('FM', 'Micronesia'),
('MD', 'Moldova'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PL', 'Poland'),
('PT', 'Portugal'),
('QA', 'Qatar'),
('RO', 'Romania'),
('RU', 'Russia'),
('RW', 'Rwanda'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('SS', 'South Sudan'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syria'),
('TW', 'Taiwan'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

INSERT INTO gamma.continents (continent_name) VALUES
('Africa'),
('Antarctica'),
('Asia'),
('Europe'),
('North America'),
('Oceania'),
('South America');

INSERT INTO gamma.botanists (email,first_name,last_name,phone) VALUES
('gertrude.jekyll@lnhm.co.uk','Gertrude', 'Jekyll','001-481-273-3691x127'),
('carl.linnaeus@lnhm.co.uk','Carl', 'Linnaeus','(146)994-1635x35992'),
('eliza.andrews@lnhm.co.uk','Eliza', 'Andrews','(846)669-6651x75948');

INSERT INTO gamma.regions (town_name,continent_id,country_id) VALUES
('Resplendor',7,29),
('South Whittier',5,188),
('Efon-Alaaye',1,134),
('Ilopango',7,59),
('Jashpurnagar',3,83),
('Markham',5,37),
('Bonoua',1,49),
('Weimar',4,71),
('Split',4,49),
('Kahului',5,188),
('Longview',5,188),
('Bensheim',4,71),
('Gainesville',5,188),
('Siliana',1,180),
('Yonkers',5,188),
('Wangon',3,84),
('Oschatz',4,71),
('Tonota',1,4),
('Reus',4,166),
('Carlos Barbosa',7,29),
('Friedberg',4,71),
('Charlottenburg-Nord',4,71),
('Ar Ruseris',1,167),
('El Achir',1,3),
('Hlukhiv',4,185),
('Brunswick',5,188),
('Ueno-ebisumachi',3,91),
('Ajdabiya',1,105),
('Licheng',3,42),
('Gifhorn',4,71),
('Bachraon',3,83),
('La Ligua',7,41),
('Dublin',5,188),
('Malaut',3,83),
('Magomeni',1,174),
('Fujioka',3,91),
('Pujali',3,83),
('Smolyan',4,31),
('Zacoalco de Torres',5,118),
('South Whittier',5,188),
('Salima',1,110),
('Catania',4,89),
('Calauan',3,143),
('Acayucan',5,118);

INSERT INTO gamma.origins (longitude,latitude,town_id) VALUES
('-19.32556', '-41.25528',1),
('33.95015', '-118.03917',2),
('7.65649', '4.92235',3),
('13.70167', '-89.10944',4),
('22.88783', '84.13864',5),
('43.86682', '-79.2663',6),
('5.27247', '-3.59625',7),
('50.9803', '11.32903',8),
('43.50891', '16.43915',9),
('20.88953', '-156.47432',10),
('32.5007', '-94.74049',11),
('49.68369', '8.61839',12),
('29.65163', '-82.32483',13),
('36.08497', '9.37082',14),
('40.93121', '-73.89875',15),
('-7.51611', '109.05389',16),
('51.30001', '13.10984',17),
('-21.44236', '27.46153',18),
('41.15612', '1.10687',19),
('-29.2975', '-51.50361',20),
('48.35693', '10.98461',21),
('52.53048', '13.29371',22),
('11.8659', '34.3869',23),
('36.06386', '4.62744',24),
('51.67822', '33.9162',25),
('43.91452', '-69.96533',26),
('34.75856', '136.13108',27),
('30.75545', '20.22625',28),
('23.29549', '113.82465',29),
('52.47774', '10.5511',30),
('28.92694', '78.23456',31),
('-32.45242', '-71.23106',32),
('32.54044', '-82.90375',33),
('30.21121', '74.4818',34),
('-6.8', '39.25',35),
('36.24624', '139.07204',36),
('22.4711', '88.1453',37),
('41.57439', '24.71204',38),
('20.22816', '-103.5687',39),
('-13.7804', '34.4587',40),
('37.49223', '15.07041',41),
('14.14989', '121.3152',42),
('17.94979', '-94.91386',43);

INSERT INTO gamma.plant_species (common_name,scientific_name) VALUES
('Epipremnum Aureum', 'Epipremnum aureum'),
('Venus Flytrap', 'Dionaea muscipula'),
('Corpse flower', 'Amorphophallus titanum'),
('Rafflesia arnoldii', 'Rafflesia arnoldii'),
('Black bat flower', 'Tacca chantrieri'),
('Pitcher plant', 'Nepenthes'),
('Wollemi pine', 'Wollemia nobilis'),
('Bird of paradise', 'Strelitzia reginae'),
('Cactus', 'Cactaceae'),
('Dragon Tree', 'Dracaena draco'),
('Asclepias Curassavica', 'Asclepias curassavica'),
('Brugmansia X Candida', 'Brugmansia × candida'),
('Canna ''Striata''', 'Canna indica'),
('Colocasia Esculenta', 'Colocasia esculenta'),
('Cuphea ''David Verity''', 'Cuphea ignea × micropetala'),
('Euphorbia Cotinifolia', 'Euphorbia cotinifolia'),
('Ipomoea Batatas', 'Ipomoea batatas'),
('Manihot Esculenta ''Variegata''', 'Manihot esculenta'),
('Musa Basjoo', 'Musa basjoo'),
('Salvia Splendens', 'Salvia splendens'),
('Anthurium', 'Anthurium andraeanum'),
('Cordyline Fruticose', 'Cordyline fruticosa'),
('Palm Trees', 'Arecaceae'),
('Dieffenbachia Seguine', 'Dieffenbachia seguine'),
('Spathipyllum', 'Spathiphyllum wallisii'),
('Croton', 'Codiaeum variegatum'),
('Aloe Vera', 'Aloe barbadensis miller'),
('Ficus Elastica', 'Ficus elastica'),
('Sansevieria Trifasciata', 'Dracaena trifasciata'),
('Philodendron Hederaceum', 'Philodendron hederaceum'),
('Schefflera Arboricola', 'Schefflera arboricola'),
('Aglaonema Commutatum', 'Aglaonema commutatum'),
('Monstera Deliciosa', 'Monstera deliciosa'),
('Tacca Integrifolia', 'Tacca integrifolia'),
('Psycopsis Papilio', 'Psychopsis papilio'),
('Saintpaulia Ionantha', 'Saintpaulia ionantha'),
('Gaillardia', 'Gaillardia aristata'),
('Caladium Bicolor', 'Caladium bicolor'),
('Chlorophytum Comosum', 'Chlorophytum comosum'),
('Araucaria Heterophylla', 'Araucaria heterophylla'),
('Begonia', 'Begonia'),
('Medinilla Magnifica', 'Medinilla magnifica'),
('Calliandra Haematocephala', 'Calliandra haematocephala'),
('Zamioculcas Zamiifolia', 'Zamioculcas zamiifolia'),
('Crassula Ovata', 'Crassula ovata');