on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  speak:
    runs-on: ubuntu-latest

    steps:
    - name: "Echo a message"
      run: echo "Job successful."

  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v4

    - name: "Install Python"
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'

    - name: "Install libraries"
      run: pip install -r requirements.txt

    - name: "Run pytest"
      run: pytest
